version: '3'

services:
  product-service:
    build: ./product-service
    container_name: product
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - GRAPHQL_ENDPOINT=http://intent-service:3001/query
    depends_on:
      - intent-service
    networks:
      - app-network

  intent-service:
    build: ./intent-service
    container_name: intent
    ports:
      - "3001:3001"
    volumes:
      - ./intent-service:/usr/src/app
    environment:
      - MONGODB_URI=mongodb://mongo:27017/MONGODB_DATABASE
      - PORT=3001
      - MONGODB_DATABASE=<your_mongodb_database_name>
    networks:
      - app-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
