version: '3'

services:
  product-service:
    build: ./product-service
    container_name: product
    ports:
      - "8080:3000"
    volumes:
      - ./product-service:/usr/src/app
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017/product-service
    depends_on:
      - mongo
    networks:
      - app-network
  
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - app-network



networks:
  app-network:
    driver: bridge
